from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

from . import spectral_clusterer_new

SpectralClusterer = spectral_clusterer_new.SpectralClusterer
DEFAULT_REFINEMENT_SEQUENCE = spectral_clusterer_new.DEFAULT_REFINEMENT_SEQUENCE
